### ISSUE TITLE
Just ran this tonight bud, ... some changes maybe ?

### ISSUE THREAD

**Issue by n0x00** [g0tmi1k/os-scripts#23] opened 2016-08-22 21:24 UTC
first off, thank you, this is brilliant (as is all your output)

here are some thinks that might need a tweak, if this project is still a thing ...

[+] Cosmetics ~ Making it different each startup
######################################################################## 100.0%
curl: (22) The requested URL returned error: 403 Forbidden
 [!] Issue downloading Shiki-Colors-Light-Menus.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
######################################################################## 100.0%
curl: (22) The requested URL returned error: 403 Forbidden
 [!] Issue downloading axiom.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
 [!] Issue downloading kali_blue_splat.png
######################################################################## 100.0%

curl: (6) Could not resolve host: www.hdwallpapers.im
 [!] Issue downloading kali_black_stripes.jpg
######################################################################## 100.0%

also 

 [+] Installing PyCharm (Community Edition) ~ Python IDE
######################################################################## 100.0%
curl: (22) The requested URL returned error: 403 Forbidden
 [!] Issue downloading pycharms-community.tar.gz
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat '/tmp/pycharm-community-*/': No such file or directory

**Comment by g0tmi1k** [comment] 2016-09-21 11:27
Cheers for the bug report!

This has been fixed in b970909a2a9e15df87ddd3ec5834e0fa01fdc12c
_It's also a duplicate of #24 & #20_

**Closed by g0tmi1k** 2016-09-21 11:27 UTC
