### ISSUE TITLE
bash_aliases command not found

### ISSUE THREAD

**Issue by CingulateCortex** [g0tmi1k/os-scripts#14] opened 2016-04-06 22:13 UTC
Hi

Thanks for the script. There is an error on bash_aliases file 

'''
/root/.bash_aliases:1: command not found: -e
/root/.bash_aliases:4: command not found: -e
'''
Somehow script added "-e" to every alias line.

Besides some icons are missing which is not a big deal.

**Comment by g0tmi1k** [comment] 2016-04-07 18:34
Thats... Odd?
How are you running the script? Whats your setup?

I've just released the kali rolling edition of the script, if you are still having issues - please let me know ~ https://github.com/g0tmi1k/os-scripts/blob/master/kali-rolling.sh

**Comment by mshari** [comment] 2016-04-23 01:28
hi 
I have the same problem
![kali-linux-2016 1-vm-amd64-2016-04-23-04-23-38](https://cloud.githubusercontent.com/assets/3765269/14758501/d99b9d28-090b-11e6-9336-d0eecc6f0df6.png)

**Comment by g0tmi1k** [comment] 2016-04-23 07:12
Thats odd. I am unable to reproduce the bug.
Please post DETAILS in your posts (OS, Version, Commands Used, Complete outputs)

**Comment by g0tmi1k** [comment] 2016-09-21 10:12
Closing the issue due to the lack of details & communication.
Please re-open it when you can provide more information.

**Closed by g0tmi1k** 2016-09-21 10:12 UTC
Labels: bug
