### ISSUE TITLE
A "cosmetic" link requires authentication

### ISSUE THREAD

**Issue by kemperature** [g0tmi1k/os-scripts#24] opened 2016-09-15 03:14 UTC
This [link](http://xfce-look.org/CONTENT/content-files/90145-axiom.tar.gz) requires authentication.
You may wanna change the link.

specific: kali-rolling.sh:705

As well as the [link of oui in Aircrack section](http://standards.ieee.org/regauth/oui/oui.txt) has been moved to [this](http://standards-oui.ieee.org/oui/oui.txt)

**Comment by g0tmi1k** [comment] 2016-09-21 11:24
Thanks for reporting both issues.

The main point (the one that's in the title) is a duplicate of #20 - which has now been fixed.
The other issue regarding aircrack-ng/ieee - I've updated link (however its still 'slow' for me - 3.6kbps down for a 3.3mb file!)

**Closed** 2016-09-21 11:25 UTC
